### PR TITLE
feat: detect iOS >=11 in-app webview short ua

### PR DESCRIPTION
**Pull request by carles-thn**
This should solve https://github.com/Financial-Times/polyfill-useragent-normaliser/pull/174
(cc @christianhaller3000 )

### CODE REVIEW

**Comment by christianhaller3000** [comment]
hmmm, on my machine the failing tests are still failing. 😞

**Comment by carles-thn** [comment]
@christianhaller3000 do you mean the test you made on https://github.com/Financial-Times/polyfill-useragent-normaliser ?
To test it you will need to update `polyfill-useragent-normaliser` to use `useragent_parser` from this branch. May be better to wait until this gets merged.

**Comment by christianhaller3000** [comment]
I cloned your branch, built it and move it to my `node_modules` to test it.

**Comment by carles-thn** [comment]
@christianhaller3000 allright, thanks, I'll look into that :)

**Review by JakeChampion — APPROVED** [review]
Thanks, I can confirm this passes the tests in CI - https://github.com/Financial-Times/useragent_parser/runs/5448349627?check_suite_focus=true#step:4:87

**Pull request merged**
